name: napari_vesuvius
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  # - napari=0.4.19
  - numpy<2
  - zarr
  - scikit-image
  - scipy
  - matplotlib
  - jupyter
  - ipykernel
  - scikit-learn
  - pyqt
  - numba
  - pip
  - pip:
    - pynrrd
    - qasync
    - blosc2
    # - napari-threedee 
    # Use patched version of napari-threedee that prevents crash
    - git+https://github.com/JamesDarby345/napari-threedee-undo-bug.git@main
    # use smoother labels fork for napari for now
    - git+https://github.com/JamesDarby345/napari-smoother-labels.git@main