name: napari_vesuvius
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - napari
  - pyqt
  - numpy<2
  - zarr
  - scikit-image
  - scipy
  - matplotlib
  - scikit-learn
  - numba
  - pip
  - pip:
    - pynrrd
    - qasync
    - blosc2
    - fastmorph
    - distinctipy
    # - napari-threedee 
    # Use patched version of napari-threedee that prevents crash
    - git+https://github.com/JamesDarby345/napari-threedee-undo-bug.git@main
