cube_info:
  # cube z,y,x coords to load correct raw data & mask cubes
  zyx: '00000_00000_00000'
  scroll_name: 's1' # dont use '_' in scroll name
  chunk_size: 256
  pad_amount: 100
  smoother_labels: True # Use smoother labels by default
  brush_size: 4
  cc_min_size: 300 # minimum number of voxels of an object to not be filtered out by connected components

  main_label_layer_name: 'papyrus' # 'papyrus' or 'ink', sets the main label layer for functions to act on.
  # Note that Scroll 1 alignment origin is 2000,2000,2000, other scrolls use 0,0,0
  align_coordinates: True # whether or not to enforce coordinates aligned to chunk size for label editing
  nrrd_cube_path: '' # Leave blank if using default nrrd cube location (data/nrrd_cubes/scroll_name), or a zarr for raw data
  voxelised_mesh_path: '' # Leave blank if using the default voxelized mesh location (data/manual_sheet_segmentation/scroll_name)
  raw_data_zarr_path: '' # Ex: '/path/to/file.zarr'
  ink_pred_zarr_path: '' # Keep empty if not using ink prediction zarrs
  create_papyrus_mask_if_not_provided: True # Create papyrus mask if not provided, turn off if just interested in ink labels for faster loading

  # Variables to align raw data and ink pred axis
  # if both raw data and ink pred zarrs of the same size are used, 
  # the variables can be left blank and the ink pred zarr axis 
  # will be automatically aligned to the raw data zarr axis
  raw_data_axis_order: 'zyx' 
  ink_pred_label_order: 'zyx'
  ink_threshold: 150 # threshold value to binarize ink prediction zarr values for display as labels
  use_custom_colormap: True # Use custom colormap for better label colors (limited to 183 colors)
  factor: 1.0 #semantic mask scale factor
  edit_chunk_size: 256 # chunk size to use when focussing on a chunk for label editing

# Napari default keybinds will overwrite the custom keybinds in some modes
# Thus, it is recommended to not use the default keybinds for custom keybinds
# Keys with default functions include:
# x,y,z,o,p,[,],-,=,m,p,1,2,3,4,5
customizable_hotkeys:
  toggle_labels_visibility: ["s","/"]
  toggle_data_visibility: ["w","."]
  erase_mode_toggle: ["Shift-w"]
  move_mode: ["Shift-s"]
  #------------------------
  #arrow keys have 2d default behaviour, these extend behaviour to 3d plane shifting
  shift_data_left_and_recut_3d_label: ["Left","Shift-q"]
  shift_data_right_and_recut_3d_label: ["Right","Shift-e"]
  shift_data_left_fast_and_recut_3d_label: "Shift-Left"
  shift_data_right_fast_and_recut_3d_label: "Shift-Right"
  #------------------------
  # emulates arrow key behaviour in 2d view, extended for 3d view also
  shift_data_left: "a"
  shift_data_right: "d"
  shift_data_left_fast: "Shift-a"
  shift_data_right_fast: "Shift-d"
  #------------------------
  plane_erase_3d_mode: ["c",","]
  plane_3d_erase_mode_shift_left: "q"
  plane_3d_erase_mode_shift_right: "e"
  cut_label_at_oblique_plane: ["Shift-v","k"]
  switch_to_plane_view: ["Shift-c","g"]
  full_label_view: "v"
  toggle_contextual_view: "t"
  toggle_preserve_labels: ""
  toggle_show_selected_label: ""
  connected_components_preview: "r"

  #l is defaulted for switching to data layer because it is near o
  #as o for off-axis plane slice is a napari default (hard to change) 
  #o is the main usecase for switching to the data layer in 3d
  switch_to_data_layer: "l"
  
  #Can be used along side arrow keys (switching layers) to find connections in 2d
  flood_fill: ["Down"]
  large_flood_fill: ["Up"]

  #------------------------
  #less often used keybinds, may have gui button, or became less useful for defaults/3d
  erode_labels: "i"
  dilate_labels: "u"
  connected_components: "'"
  #TODO: document these new keybinds
  reset_plane_to_default: "b"
  reset_plane_view_to_default: "Shift-b"
  align_plane_with_selected_label: "n"
  align_cube_with_selected_label: "Shift-n"

  save_labels: "h"
  decrease_brush_size: "Shift-z"
  increase_brush_size: "Shift-x"
  toggle_show_selected_label: ""
  set_corner_view: ""
