#Napari default keybinds will overwrite custome keybinds in some modes
#Keys with default functions include:
#x,y,z,o,p,[,],-,=
customizable_hotkeys:
  toggle_labels_visibility: ["/", "r"]
  toggle_data_visibility: [".", "t"]
  on_left_arrow_event: "Left"
  on_right_arrow_event: "Right"
  on_shift_left_arrow_event: "Shift-Left" 
  on_shift_right_arrow_event: "Shift-Right"  
  cut_label_at_oblique_plane: "k"
  switch_to_data_layer: "l"
  full_label_view: "b"
  switch_to_plane: "\\"
  erase_3d_mode: "'"
  move_mode: ";"
  plane_erase_3d_mode: "," 
  erode_labels: "i"
  dilate_labels: "u"
  add_padding_contextual_data: "j"
  connected_components: "c"
  flood_fill: ["f", "Down"]
  large_flood_fill: ["g", "Up"]
  save_labels: "h"
  draw_compressed_class: "v"
  decrease_brush_size: "q"
  increase_brush_size: "e"
  label_picker: "w"
  toggle_show_selected_label: "s"
  shift_dim_left: "a"
  shift_dim_right: "d"
  interpolate_borders: "x"